version: '3.8'

services:
  mosquitto:
    build:
      context: .
    volumes:
      - type: bind
        source: ./config/
        target: /mosquitto/config/
      - type: bind
        source: ./log/
        target: /mosquitto/log/
      - type: volume
        source: mqtt-broker-data
        target: /mosquitto/data/
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host

  mongo:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data

  mqtt_publisher:
    build:
      context: .
      dockerfile: ./scripts/publisher/Dockerfile
    depends_on:
      - mosquitto

  mqtt_subscriber:
    build:
      context: .
      dockerfile: ./scripts/subscriber/Dockerfile
    depends_on:
      - mosquitto
      - mongo
      - cache

  fastapi_app:
    build:
      context: .
      dockerfile: ./scripts/fastapi/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - cache

volumes:
  mqtt-broker-data:
    name: "mqtt-broker-data"
  mongo-data:
  cache:
    driver: local
